[package]
name = "blinky"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-xbuild]
memcpy = true

[dependencies]
rand_core = {version = "0.5.1" }
rand = {version = "0.7.3", default-features = false }
